version: 2

sphinx:
  configuration: korp.sdk-documentation/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: korp.sdk-documentation/requirements.txt